### ISSUE TITLE
使用过程中报段错误

### ISSUE THREAD

**Issue by jerryjoejj** [QijingZheng/Hefei-NAMD#6]
您好，按照文档中的方法编译运行后报段错误，更换了多个软硬件平台还是有问题，麻烦您帮忙看下，谢谢！
![image](https://user-images.githubusercontent.com/7274047/88454546-078e9f80-cea3-11ea-815a-c06c6b53539c.png)

**Comment by QijingZheng** [comment]
根据输出显示NSW = 100，但是NAMDTIME = 500，原则上NAMDTINI + NAMDTIME <= NSW，不然会有溢出的问题。

**Comment by jerryjoejj** [comment]
问题解决了，计算结果没问题，感谢感谢！
